"""create initial salon tables

Revision ID: 71452eee3e3f
Revises: 
Create Date: 2026-04-18 17:08:27.226767
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '71452eee3e3f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'stylist', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('salons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('default_slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salons_id'), 'salons', ['id'], unique=False)
    op.create_index(op.f('ix_salons_owner_user_id'), 'salons', ['owner_user_id'], unique=False)
    op.create_table('salon_operating_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salon_id', 'day_of_week')
    )
    op.create_index(op.f('ix_salon_operating_hours_day_of_week'), 'salon_operating_hours', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_salon_operating_hours_id'), 'salon_operating_hours', ['id'], unique=False)
    op.create_index(op.f('ix_salon_operating_hours_salon_id'), 'salon_operating_hours', ['salon_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_is_active'), 'services', ['is_active'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_salon_id'), 'services', ['salon_id'], unique=False)
    op.create_table('stylists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_stylists_id'), 'stylists', ['id'], unique=False)
    op.create_index(op.f('ix_stylists_is_active'), 'stylists', ['is_active'], unique=False)
    op.create_index(op.f('ix_stylists_salon_id'), 'stylists', ['salon_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('stylist_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('starts_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('booked', 'completed', 'cancelled', 'no_show', name='bookingstatus'), nullable=False),
    sa.Column('booking_type', sa.Enum('online', 'walk_in', name='bookingtype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['stylist_id'], ['stylists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_ends_at_utc'), 'bookings', ['ends_at_utc'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_local_date'), 'bookings', ['local_date'], unique=False)
    op.create_index(op.f('ix_bookings_salon_id'), 'bookings', ['salon_id'], unique=False)
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_index(op.f('ix_bookings_starts_at_utc'), 'bookings', ['starts_at_utc'], unique=False)
    op.create_index(op.f('ix_bookings_stylist_id'), 'bookings', ['stylist_id'], unique=False)
    op.create_table('stylist_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stylist_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stylist_id'], ['stylists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stylist_availability_day_of_week'), 'stylist_availability', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_stylist_availability_id'), 'stylist_availability', ['id'], unique=False)
    op.create_index(op.f('ix_stylist_availability_stylist_id'), 'stylist_availability', ['stylist_id'], unique=False)
    op.create_table('stylist_specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stylist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stylist_id'], ['stylists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stylist_specialties_id'), 'stylist_specialties', ['id'], unique=False)
    op.create_index(op.f('ix_stylist_specialties_name'), 'stylist_specialties', ['name'], unique=False)
    op.create_index(op.f('ix_stylist_specialties_stylist_id'), 'stylist_specialties', ['stylist_id'], unique=False)
    op.create_table('booking_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'paid', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_booking_charges_id'), 'booking_charges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_charges_id'), table_name='booking_charges')
    op.drop_table('booking_charges')
    op.drop_index(op.f('ix_stylist_specialties_stylist_id'), table_name='stylist_specialties')
    op.drop_index(op.f('ix_stylist_specialties_name'), table_name='stylist_specialties')
    op.drop_index(op.f('ix_stylist_specialties_id'), table_name='stylist_specialties')
    op.drop_table('stylist_specialties')
    op.drop_index(op.f('ix_stylist_availability_stylist_id'), table_name='stylist_availability')
    op.drop_index(op.f('ix_stylist_availability_id'), table_name='stylist_availability')
    op.drop_index(op.f('ix_stylist_availability_day_of_week'), table_name='stylist_availability')
    op.drop_table('stylist_availability')
    op.drop_index(op.f('ix_bookings_stylist_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_starts_at_utc'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_salon_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_local_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_ends_at_utc'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_stylists_salon_id'), table_name='stylists')
    op.drop_index(op.f('ix_stylists_is_active'), table_name='stylists')
    op.drop_index(op.f('ix_stylists_id'), table_name='stylists')
    op.drop_table('stylists')
    op.drop_index(op.f('ix_services_salon_id'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_is_active'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_salon_operating_hours_salon_id'), table_name='salon_operating_hours')
    op.drop_index(op.f('ix_salon_operating_hours_id'), table_name='salon_operating_hours')
    op.drop_index(op.f('ix_salon_operating_hours_day_of_week'), table_name='salon_operating_hours')
    op.drop_table('salon_operating_hours')
    op.drop_index(op.f('ix_salons_owner_user_id'), table_name='salons')
    op.drop_index(op.f('ix_salons_id'), table_name='salons')
    op.drop_table('salons')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
